[workspace]
members         = ["crates/assetpack-core", "crates/assetpack-transform-precomp2"]
package.edition = "2024"
resolver        = "2"

  [workspace.dependencies]
  assetpack-core = { version = "0.2", path = "crates/assetpack-core" }
  brotli = "8.0"
  chrono = "0.4"
  fastcdc = "3.2"
  futures-core = "0.3"
  futures-util = "0.3"
  hex = "0.4"
  lzma-rust2 = "0.16"
  precomp2 = "0.1"
  rand = "0.9"
  serde = { version = "1.0", features = ["derive"] }
  sha3 = "0.11"
  sqlx = { version = "0.8", default-features = false, features = [
    "sqlite",
    "runtime-tokio",
    "chrono",
  ] }
  tempfile = "3.27"
  thiserror = "2.0"
  tokio = { version = "1.37", features = ["fs", "sync"] }
  zstd = "0.13"
