[package]
edition = "2024"
name    = "assetpack-core-fuzz"
publish = false
version = "0.0.0"

  [package.metadata]
  cargo-fuzz = true

[dependencies]
assetpack-core = { path = "../crates/assetpack-core", default-features = false, features = [
  "sealed-encryption",
] }
libfuzzer-sys = "0.4"

[[bin]]
bench = false
doc   = false
name  = "sealed_open_plain"
path  = "fuzz_targets/sealed_open_plain.rs"
test  = false

[[bin]]
bench = false
doc   = false
name  = "sealed_open_encrypted"
path  = "fuzz_targets/sealed_open_encrypted.rs"
test  = false

[[bin]]
bench = false
doc   = false
name  = "file_reader"
path  = "fuzz_targets/file_reader.rs"
test  = false

[workspace]
